import time
time_s = 0.2
print('+++')
time.sleep(time_s)
print('++++')
time.sleep(time_s)
print('++ ++')
time.sleep(time_s)
print(' ++ ++')
time.sleep(time_s)
print('  ++ ++')
time.sleep(time_s)
print('   ++ ++')
time.sleep(time_s)
print('    ++ ++')
time.sleep(time_s)
print('     ++ ++')
time.sleep(time_s)
print('      ++ ++')
time.sleep(time_s)
print('       ++ ++')
time.sleep(time_s)
print('        ++ ++')
time.sleep(time_s)
print('         ++ ++')
time.sleep(time_s)
print('          ++ ++             *')
time.sleep(time_s)
print('           ++ ++            **')
time.sleep(time_s)
print('            ++ ++            **')
time.sleep(time_s)
print('             ++ ++           ***')
time.sleep(time_s)
print('              ++ ++           ***')
time.sleep(time_s)
print('               ++ ++          ***')
time.sleep(time_s)
print('                ++ ++        ****')
time.sleep(time_s)
print('                 ++ ++      ****')
time.sleep(time_s)
print('                  ++ ++    ****')
time.sleep(time_s)
print('                   ++ ++  ****')
time.sleep(time_s)
print('                    ++ ++****')
time.sleep(time_s)
print('                     +++****')
time.sleep(time_s)
print('                      +****')
time.sleep(time_s)
print('                       ****%%')
time.sleep(time_s)
print('                      ****%%%%')
time.sleep(time_s)
print('                     ****  %%%%')
time.sleep(time_s)
print('            *       ****    %%%%')
time.sleep(time_s)
print('             **    ****      %%%%')
time.sleep(time_s)
print('              *** ****        %%%%')
time.sleep(time_s)
print('               ******          %%%%')
time.sleep(time_s)
print('                ****            %%%%')
time.sleep(time_s)
print('                                 %%%$$$')
time.sleep(time_s)
print('                                  %$$$$$')
time.sleep(time_s)
print('                                  $$$$$$$')
time.sleep(time_s)
print('                                  $$$$$$$')
time.sleep(time_s)
print('                                   $$$$$')
time.sleep(time_s)
print('                                    $$$')  
